// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CodeSnippet struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type CompilationResult struct {
	ID            string `json:"id"`
	CodeSnippetID string `json:"codeSnippetId"`
	Output        string `json:"output"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type CompletionChunk struct {
	Text   string `json:"text"`
	IsLast bool   `json:"isLast"`
}

type Error struct {
	Message      string `json:"message"`
	LineNumber   *int   `json:"lineNumber,omitempty"`
	ColumnNumber *int   `json:"columnNumber,omitempty"`
}

type Explanation struct {
	ID            string `json:"id"`
	CodeSnippetID string `json:"codeSnippetId"`
	Explanation   string `json:"explanation"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
