/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/E4G1IPk8fvw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { MenubarTrigger, MenubarItem, MenubarSeparator, MenubarContent, MenubarMenu, Menubar } from "@/components/ui/menubar"
import { Textarea } from "@/components/ui/textarea"
import { ModeToggle } from "@/components/mode-toggle"

export function CUDALiveConverter2() {
  return (
    <>
      <Menubar>
        <MenubarMenu>
          <h1 className="text-lg font-medium p-4">CUDA Live Converter</h1>
          <MenubarTrigger>File</MenubarTrigger>
          <MenubarContent>
            <MenubarItem>New</MenubarItem>
            <MenubarItem>Open</MenubarItem>
            <MenubarSeparator />
            <MenubarItem>Save</MenubarItem>
            <MenubarItem>Save As</MenubarItem>
          </MenubarContent>
        </MenubarMenu>
        <MenubarMenu>
          <MenubarTrigger>Edit</MenubarTrigger>
          <MenubarContent>
            <MenubarItem>Undo</MenubarItem>
            <MenubarItem>Redo</MenubarItem>
            <MenubarSeparator />
            <MenubarItem>Cut</MenubarItem>
            <MenubarItem>Copy</MenubarItem>
            <MenubarItem>Paste</MenubarItem>
          </MenubarContent>
        </MenubarMenu>
        <MenubarMenu>
          <MenubarTrigger>View</MenubarTrigger>
          <MenubarContent>
            <MenubarItem>Theme</MenubarItem>
            <MenubarItem>Font Size</MenubarItem>
            <MenubarSeparator />
            <MenubarItem>Word Wrap</MenubarItem>
            <MenubarItem>Line Numbers</MenubarItem>
          </MenubarContent>
        </MenubarMenu>
        <MenubarMenu>
          <MenubarTrigger>Help</MenubarTrigger>
          <MenubarContent>
            <MenubarItem>Documentation</MenubarItem>
            <MenubarItem>Keyboard Shortcuts</MenubarItem>
            <MenubarSeparator />
              <ModeToggle />
          </MenubarContent>
        </MenubarMenu>
      </Menubar>
      <div className="flex h-screen">
        <div className="w-1/2 border-r border-gray-200 dark:border-gray-800 p-6 flex flex-col">
          <div className="text-lg font-medium mb-4">Python Code</div>
          <Textarea
            className="flex-1 bg-gray-100 dark:bg-gray-950 rounded-md p-4 text-sm font-mono"
            placeholder="Enter your Python code here..."
          />
        </div>
        <div className="w-1/2 p-6 flex flex-col">
          <div className="text-lg font-medium mb-4">Triton Code Output</div>
          <div className="flex-1 bg-gray-100 dark:bg-gray-950 rounded-md p-4 text-sm font-mono overflow-auto">
            <pre>
              import triton # Your Python code goes here x = torch.randn(1, 3, 224, 224) model =
              triton.load_model('path/to/model.pt') y = model(x) print(y)
            </pre>
          </div>
        </div>
      </div>
    </>
  )
}
