/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/D4kdy7xbAcR
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Textarea } from "@/components/ui/textarea"

export function CUDALiveConverter() {
  return (
    <div className="flex h-screen">
      <div className="w-1/2 border-r border-gray-200 dark:border-gray-800 p-6 flex flex-col">
        <div className="text-lg font-medium mb-4">Python Code</div>
        <Textarea
          className="flex-1 bg-gray-100 dark:bg-gray-950 rounded-md p-4 text-sm font-mono"
          placeholder="Enter your Python code here..."
        />
      </div>
      <div className="w-1/2 p-6 flex flex-col">
        <div className="text-lg font-medium mb-4">Triton Code Output</div>
        <div className="flex-1 bg-gray-100 dark:bg-gray-950 rounded-md p-4 text-sm font-mono overflow-auto">
          <pre>
            import triton # Your Python code goes here x = torch.randn(1, 3, 224, 224) model =
            triton.load_model('path/to/model.pt') y = model(x) print(y)
          </pre>
        </div>
      </div>
    </div>
  )
}
